__author__ = 'andreas'

import csv
import numpy as np

data1 = np.loadtxt('data/right-slow-10.csv', delimiter=',')
data2 = np.loadtxt('data/left-slow-10.csv', delimiter=',')
data3 = np.loadtxt('data/right-fast-10.csv', delimiter=',')
data4 = np.loadtxt('data/left-fast-10.csv', delimiter=',')
data5 = np.loadtxt('data/up-slow-10.csv', delimiter=',')
data6 = np.loadtxt('data/down-slow-10.csv', delimiter=',')
data7 = np.loadtxt('data/up-fast-10.csv', delimiter=',')
data8 = np.loadtxt('data/down-fast-10.csv', delimiter=',')
data9 = np.loadtxt('data/far-10.csv', delimiter=',')
data10 = np.loadtxt('data/near-10.csv', delimiter=',')

data11 = np.loadtxt('data/cover1-10.csv', delimiter=',')
data12 = np.loadtxt('data/cover2-10.csv', delimiter=',')
data13 = np.loadtxt('data/cover3-10.csv', delimiter=',')
data14 = np.loadtxt('data/cover4-10.csv', delimiter=',')
data15 = np.loadtxt('data/lowright-slow-10.csv', delimiter=',')
data16 = np.loadtxt('data/lowleft-slow-10.csv', delimiter=',')
data17 = np.loadtxt('data/lowright-fast-10.csv', delimiter=',')
data18 = np.loadtxt('data/lowleft-fast-10.csv', delimiter=',')
data19 = np.loadtxt('data/left-circle-10.csv', delimiter=',')
data20 = np.loadtxt('data/right-circle-10.csv', delimiter=',')

data21 = np.loadtxt('data/cover12-10.csv', delimiter=',')
data22 = np.loadtxt('data/cover34-10.csv', delimiter=',')
data23 = np.loadtxt('data/cover13-10.csv', delimiter=',')
data24 = np.loadtxt('data/cover24-10.csv', delimiter=',')
data25 = np.loadtxt('data/cover14-10.csv', delimiter=',')
data26 = np.loadtxt('data/cover23-10.csv', delimiter=',')
data27 = np.loadtxt('data/upeast-slow-10.csv', delimiter=',')
data28 = np.loadtxt('data/downeast-slow-10.csv', delimiter=',')
data29 = np.loadtxt('data/upwest-slow-10.csv', delimiter=',')
data30 = np.loadtxt('data/downwest-slow-10.csv', delimiter=',')
data31 = np.loadtxt('data/upeast-fast-10.csv', delimiter=',')
data32 = np.loadtxt('data/downeast-fast-10.csv', delimiter=',')
data33 = np.loadtxt('data/upwest-fast-10.csv', delimiter=',')
data34 = np.loadtxt('data/downwest-fast-10.csv', delimiter=',')

data35 = np.loadtxt('data/nw-slow-10.csv', delimiter=',')
data36 = np.loadtxt('data/nw-fast-10.csv', delimiter=',')
data37 = np.loadtxt('data/ne-slow-10.csv', delimiter=',')
data38 = np.loadtxt('data/ne-fast-10.csv', delimiter=',')
data39 = np.loadtxt('data/sw-slow-10.csv', delimiter=',')
data40 = np.loadtxt('data/sw-fast-10.csv', delimiter=',')
data41 = np.loadtxt('data/se-slow-10.csv', delimiter=',')
data42 = np.loadtxt('data/se-fast-10.csv', delimiter=',')

partition = 1

with open('data/40-10.csv', 'w') as fp:
    a = csv.writer(fp, delimiter=',')
    a.writerows(data1[:len(data1)/partition])
    a.writerows(data2[:len(data2)/partition])
    a.writerows(data3[:len(data3)/partition])
    a.writerows(data4[:len(data4)/partition])
    a.writerows(data5[:len(data5)/partition])
    a.writerows(data6[:len(data6)/partition])
    a.writerows(data7[:len(data7)/partition])
    a.writerows(data8[:len(data8)/partition])
    a.writerows(data9[:len(data9)/partition])
    a.writerows(data10[:len(data10)/partition])

    a.writerows(data11[:len(data11)/partition])
    a.writerows(data12[:len(data12)/partition])
    a.writerows(data13[:len(data13)/partition])
    a.writerows(data14[:len(data14)/partition])
    a.writerows(data15[:len(data15)/partition])
    a.writerows(data16[:len(data16)/partition])
    a.writerows(data17[:len(data17)/partition])
    a.writerows(data18[:len(data18)/partition])
    a.writerows(data19[:len(data19)/partition])
    a.writerows(data20[:len(data20)/partition])

    a.writerows(data21[:len(data21)/partition])
    a.writerows(data22[:len(data22)/partition])
    a.writerows(data23[:len(data23)/partition])
    a.writerows(data24[:len(data24)/partition])
    a.writerows(data25[:len(data25)/partition])
    a.writerows(data26[:len(data26)/partition])
    a.writerows(data27[:len(data27)/partition])
    a.writerows(data28[:len(data28)/partition])
    a.writerows(data29[:len(data29)/partition])
    a.writerows(data30[:len(data30)/partition])
    a.writerows(data31[:len(data31)/partition])
    a.writerows(data32[:len(data32)/partition])
    a.writerows(data33[:len(data33)/partition])
    a.writerows(data34[:len(data34)/partition])

    a.writerows(data35[:len(data35)/partition])
    a.writerows(data36[:len(data36)/partition])
    a.writerows(data37[:len(data37)/partition])
    a.writerows(data38[:len(data38)/partition])
    a.writerows(data39[:len(data39)/partition])
    a.writerows(data40[:len(data40)/partition])
    a.writerows(data41[:len(data41)/partition])
    a.writerows(data42[:len(data42)/partition])


